export const LOGIN_USER_PENDING = "login_user_pending"
export const LOGIN_USER = "login_user"
export const LOGIN_USER_ERROR = "login_user_error"
export const LOGIN_USER_SUCCESS = "login_user_success"
export const REGISTER_USER = "register_user"
export const AUTH_USER = "auth_user"